# -*- coding: utf-8 -*-
"""aprendendo_numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETqP7CqpFpyKgVamIZshv_QE6_eYvZmN

Numpy é ....
"""

import numpy as np

"""A estrutura de dados mais importante do numpy é o array. O array é uma matriz multidimensional com operadores de álgebra."""

#criar um array a partir de uma lista
v=np.array([2,4,7])
print("vetor criado a partir de lista:", v)
print("segundo elemento do vetor: ",v[1])

#criar um array a partir de uma lista multidimensional
M=np.array(([2,5,3],[9,1,7]))
print("matriz criada a partir de lista multidimensional: \n", M)
print("primeiro elemento da segunda linha: ",M[(1,0)])

#também é possível usar slices em arrays
print("segundo coluna da matriz: ",M[1, 2:4])

"""Existem várias maneiras de criar arrays: pode ser um array apenas com zeros, apenas com uns ou identidade."""

#criando matriz com zeros
A=np.zeros((3,3))
print("zeros: \n",A)
#criando matriz com uns
B=np.ones((3,3))
print("uns: \n",B)
#criando matriz identidade
C=np.eye(3)
print("identidade: \n",C)

"""O formato do arrray (número de linhas x número de colunas) é dado pelo "shape"."""

A=np.array(([1,2],[3,4],[5,6]))
print(A)
print("formato: ", A.shape)
print("n° de linhas : ", A.shape[0])
print("n° de colunas: ", A.shape[1])

"""Diversas operações matemática podem ser realizadas com arrays, incluindo operações algébricas entre matrizes."""

A=np.array(([1,2],[1,2]))
print("A:\n",A)
B=np.array(([3,1],[2,1]))
print("B:\n",B)

#multiplicação ponto a ponto
C=A*B
print("C=A*B:\n",C)

#multiplicação de matrizes
D=np.matmul(A,B)
print("D=A*B:\n",D)

#divisão ponto a ponto
E=A/B
print("E=A/B:\n",E)

#soma
F=A+B
print("F=A+B:\n",F)

#subtração
G=A+B
print("G=A-B:\n",G)

#matriz inversa
H=np.linalg.inv(B)
print("Matriz inversa de B:\n",H)