# -*- coding: utf-8 -*-
"""aprendendo_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oxcAiGre8AWsRCx92lFHjgxYRHJhabn3
"""

O matplotlib é uma biblioteca muito usada para gráficos, funciona de forma integrada com o Numpy e sua documentação está em https://matplotlib.org/
Inicialmente vamos importar a biblioteca. COmo utilizaremos também o numpy, vamos importar ele também.

import numpy as np
import matplotlib.pyplot as plt

"""Vamos criar um gráfico simples, plotando o resultado de uma função linear."""

x=np.array((0,1,2,3,4,5,6,7,8,9,10))
y1=0.5*x+5
y2=0.3*x+12
y3=np.sin(x)+8 #função seno
#cria um grafico simples

plt.plot(x,y1,'r-') #vermelho 'r' linha -
plt.plot(x,y2,'b--') #azul 'b' linha --
plt.plot(x,y3,'gs') #verde 'g', sem linha, com marcado quadrado 's'

#mostra o grafico
plt.show()

"""Também é possível definir os parâmetros de forma explícita."""

#cria um gráfico simples
plt.plot(x,y1, color='red', linewidth=3)
plt.plot(x,y2, color='blue', marker='*', linestyle='dashed',linewidth=1,markersize=12)
plt.plot(x,y3, color=(0,0.5,0.25),marker='s',linestyle='none',markersize=12)

plt.show()