# -*- coding: utf-8 -*-
"""CD_exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bcnuM-ESa5d0dDXep-cxOEr5e_NmvgNt

Crie no seu computador um arquivo de texto plano que é uma lista de nomes. Faça o upload do arquivo para o colab e em um programa verifique se o seu nome está na lista.
"""

#abre o arquivo no modo leitura "r"
f=open("lista_nomes.txt","r")
#lê todas as linhas do texto
linhas=f.readlines()
#remover quebras de linhas
linhas = [nome.strip() for nome in linhas]

nome_busca = 'Guilherme'
for numero_linha, nome in enumerate(linhas,start=1):
  if nome.strip() == nome_busca:
    print(f"O nome '{nome_busca}' está na posição {numero_linha}: {nome.strip()} ")