# -*- coding: utf-8 -*-
"""cd_exercicio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEx4bNjenQ1PaSFSAia2wTCcK2zBTNvy

Exercício: Cria uma planilha de Excel com as seguintes colunas com valores ficítios: "nota1", "nota2" e "nota3". Carrega ela com Pandas no Python e cria uma nova coluna com a média das 3 notas, salve o dataframe resultante como outro arquivo excel.
"""

import numpy as np
import pandas as pd

df=pd.read_excel('notas.xlsx')
print(df)

medias=[]

for i in range(df.shape[0]):
  media=(df["nota1"][i]+df["nota2"][i]+df["nota3"][i])/3
  media=media.round(1)
  medias.append(media)

df["médias"]=medias
print(df)

df.to_excel('notas2.xlsx')