# -*- coding: utf-8 -*-
"""exercicio_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12uaIyVpd5BlLo42c4QUGoOqdNO915prd

Crie uma classe Retângulo, com os atributos fundamentais que definem um retângulo e um método que devolve como resultado a área do retângulo. Crie duas instâncias diferentes para demostrar a classe.
"""

class Retangulo:
  def __init__(self,alt,larg):
    self.alt=alt
    self.larg=larg
  def area(self):
    area=self.alt*self.larg
    return area

r1=Retangulo(5,10)
print(r1.area())
r2=Retangulo(2,5)
print(r2.area())
print(r1)