# -*- coding: utf-8 -*-
"""exercicio_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SHALPWSJWen9cJPE8D8hiY7NUJvgSr3q

Crie uma planilha no excel com os seguintes campos: cor, ano, potência. No Python, crie uma classe carro que tem os atributos cor, ano e potência e crie o código que carrega os dados da planilha e cria uma lista de objetos carro.
"""

import pandas as pd

class Carro:
  def __init__(self,cor,ano,potencia):
    self.cor=cor
    self.ano=ano
    self.potencia=potencia
  def __str__(self):
    return "carro de cor "+str(self.cor)+", ano "+str(self.ano)+" e potencia de "+str(self.potencia)+" cavalos"

listacarros=[]

df=pd.read_excel('/content/exercicio_4_planilha.xlsx')
print(df)

for index,row in df.iterrows():
  cor=row['cor']
  ano=row['ano']
  potencia=row['potencia']

  carro=Carro(cor,ano,potencia)
  listacarros.append(carro)

for carro in listacarros:
  print(carro)