# -*- coding: utf-8 -*-
"""manipulando_arquivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kA2VjF3986cgxEMXDECcEN6_Q0px7-Ab

O Python pode manipular arquivos (criar, ler, escrever) tanto em um nível mais baixo, ou seja, lendo e escrevendo byte por byte, quanto em um nível mais alto de abstração, interpretando uma planilha, por exemplo.
Vamos iniciar abrindo um arquivo e lendo seu conteúdo.

A função open() recebe dois parâmetros, o nome do arquivo (caminho) e o modo, os modos são:

"r" (read) apenas leitura, retorna erro se o arquivo não existe.
"a" (append) abre o arquivo e permite adicionar mais dados ao final do arquivo. Se o arquivo não existe, cria um arquivo novo.
"w" (write) cria arquivo para escrita, se o arquivo já existe, cria um arquivo novo vazio.
"x" cria o arquivo e retorna erro se o arquivo já existe.
também podemos adicionar uma letra para o modo:
"t" modo texto (conforme codificação de caracteres)
"b" modo binário (apenas os valores dos bits)
"""

#abre arquivo no modo leitura
f=open("exemplo_texto.txt","rt")
#lê todas as linhas do texto
linhas=f.readlines()
#imprimir cada linha da lista de linhas
for linha in linhas:
  print(linha,end="") #end="" para não colocar o nova linha do print

"""Nem sempre é uma boa ideia ler todas as linhas do texto se o tamanho do arquivo é desconhecido ou muito grande."""

#abre o arquivo no modo leitura e texto "rt"
f=open("exemplo_texto.txt","rt")
#lê todas as linhas do texto
linha="*"
while linha!="":
  linha=f.readline()
  if linha!="":
    print(linha)
  else: # se linha é vazia
    break #sai fora do laço de repetição
f.close()#fecha o arquivo

"""Para escrever em um arquivo, usamos os comandos write(v) escreve v, onde v é uma string ou um byte writelines(list) escreve uma lista de strings.
Vamos fazer um programa que escreve a tabuada do 7.
"""

#cria um arquivo texto de escrita
f=open("tabuada7.txt","wt")
f.write("tabuada do 7:")

for i in range(10):
  linha="7x"+str(i)+" = "+str(i*7)+"\n"
  f.write(linha)
f.close()

"""Isso também é possível utilizando o writelines()."""

texto=[]
for i in range(10):
  linha="8x"+str(i)+" = "+str(i*8)+"\n"
  texto.append(linha)

f=open("tabuada8.txt","wt")
f.write("tabuada do 8: \n")
f.writelines(texto)
f.close()